name: Example workflow

on:
  push:
    branches:
      - "**"
      - "!master"


jobs:
  example:
    name: Example
    runs-on: ubuntu-latest

    steps:
    - name: Get next version
      id: get_next_version
      uses: hugcabbage/next-version
      with:
        prefix: 'v' # optional, defaults to ''
        mode: 3
    - name: Show the next version
      run: |
        echo ${{ steps.get_next_version.outputs.version }}